//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalNoSql_CSharp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalNoSql_CSharp.Resource.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: .
        /// </summary>
        public static string Directory_not_found {
            get {
                return ResourceManager.GetString("Directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty array for parameter:.
        /// </summary>
        public static string Empty_array_for_parameter {
            get {
                return ResourceManager.GetString("Empty_array_for_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string for parameter: .
        /// </summary>
        public static string Empty_string_for_parameter {
            get {
                return ResourceManager.GetString("Empty_string_for_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters for parameter: .
        /// </summary>
        public static string Invalid_characters_for_parameter {
            get {
                return ResourceManager.GetString("Invalid_characters_for_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Id&quot; column is mandatory and must be unique..
        /// </summary>
        public static string InvalidDocumentId {
            get {
                return ResourceManager.GetString("InvalidDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using root directory to store databases is not allowed. Please create at least one subdirectory in your tree of directories..
        /// </summary>
        public static string Root_directory_not_allowed {
            get {
                return ResourceManager.GetString("Root_directory_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For testing Lock and Unlock methods you need to set into project properties -&gt; Build -&gt; Conditional compilation symbols: TEST_LOCK.
        /// </summary>
        public static string TEST_LOCK_Exception {
            get {
                return ResourceManager.GetString("TEST_LOCK_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection already exists..
        /// </summary>
        public static string This_collection_already_exists {
            get {
                return ResourceManager.GetString("This_collection_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection does not exists..
        /// </summary>
        public static string This_collection_does_not_exists {
            get {
                return ResourceManager.GetString("This_collection_does_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the collection..
        /// </summary>
        public static string Unable_to_create_the_collection {
            get {
                return ResourceManager.GetString("Unable_to_create_the_collection", resourceCulture);
            }
        }
    }
}
